In [2]:
# Supress Warnings
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd
import math

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [4]:
movies = pd.read_csv("MovieData.xls")
movies.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

-  ### Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

In [5]:
movies.shape
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
color                        5024 non-null object
director_name                4939 non-null object
num_critic_for_reviews       4993 non-null float64
duration                     5028 non-null float64
director_facebook_likes      4939 non-null float64
actor_3_facebook_likes       5020 non-null float64
actor_2_name                 5030 non-null object
actor_1_facebook_likes       5036 non-null float64
gross                        4159 non-null float64
genres                       5043 non-null object
actor_1_name                 5036 non-null object
movie_title                  5043 non-null object
num_voted_users              5043 non-null int64
cast_total_facebook_likes    5043 non-null int64
actor_3_name                 5020 non-null object
facenumber_in_poster         5030 non-null float64
plot_keywords                4890 non-null object
movie_imdb_link              5043 non-null object
num_user_for_reviews         5022 non-null float64
language                     5031 non-null object
country                      5038 non-null object
content_rating               4740 non-null object
budget                       4551 non-null float64
title_year                   4935 non-null float64
actor_2_facebook_likes       5030 non-null float64
imdb_score                   5043 non-null float64
aspect_ratio                 4714 non-null float64
movie_facebook_likes         5043 non-null int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [6]:
# Write your code for column-wise null count here
movies.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [7]:
# Write your code for row-wise null count here
movies.isnull().sum(axis = 1)

0        0
1        0
2        0
3        0
4       14
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
5013     2
5014     2
5015     0
5016     5
5017     2
5018     2
5019     2
5020     5
5021     1
5022     4
5023     2
5024     1
5025     0
5026     0
5027     0
5028     3
5029     1
5030     5
5031     3
5032     4
5033     0
5034     1
5035     0
5036     3
5037     1
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [11]:
# Write your code for column-wise null percentages here
pe = ((movies.isnull() | movies.isna()).sum() * 100 / len(movies)).round(2)
pe

director_name             0.07
num_critic_for_reviews    0.07
gross                     0.00
genres                    0.00
actor_1_name              0.10
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.02
language                  0.07
budget                    6.44
title_year                0.07
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [9]:
movies.drop(columns=['color','director_facebook_likes','actor_1_facebook_likes','actor_2_facebook_likes','actor_3_facebook_likes','actor_2_name','cast_total_facebook_likes','actor_3_name','duration','facenumber_in_poster','content_rating','country','movie_imdb_link','aspect_ratio','plot_keywords'],inplace=True)

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

In [12]:
# Write your code for dropping the rows here
col = ''
for i in pe:
    if i >= 5:
        print(i)
        col = pe[pe == i].index[0]
        #print(type(col),col)
        movies = movies[movies[col].notnull()]
        #print("done")

6.44

-  ### Subtask 2.4: Drop unecessary rows

Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [13]:
# Write your code for dropping the rows here
#movies.isnull().sum()
movies.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000

-  ### Subtask 2.5: Fill NaN values

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [14]:
# Write youprint(df['Landsize'].describe())
movies['language'].fillna('English', inplace=True)
movies.isnull().sum()

director_name             0
num_critic_for_reviews    1
gross                     0
genres                    0
actor_1_name              3
movie_title               0
num_voted_users           0
num_user_for_reviews      0
language                  0
budget                    0
title_year                0
imdb_score                0
movie_facebook_likes      0
dtype: int64

-  ### Subtask 2.6: Check the number of retained rows

You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [15]:
# Write your code for checking number of retained rows here
pe =((movies.isnull() | movies.isna()).sum() * 100 / len(movies)).round(2)
data = (3891/5042)*100
print(data)

77.1717572391908

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

## Task 3: Data Analysis
-  ### Subtask 3.1: Change the unit of columns
Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [16]:
# Write your code for unit conversion here
movies['gross'] = movies['gross']/1000000
movies['budget'] = movies['budget']/1000000
movies.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300.0,2007.0,7.1,0
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.7,2012.0,6.6,24000

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [17]:
# Write your code for creating the profit column here
movies['profit'] = movies['gross'] - movies['budget']

In [18]:
# Write your code for sorting the dataframe her
final_df = movies.sort_values(by=['profit'], ascending=False)
final_df.head(11)

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.449459
794,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
17,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.783777
240,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.544677
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.316061
439,Gary Ross,673.0,407.999255,Adventure|Drama|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games,701607,1959.0,English,78.0,2012.0,7.3,140000,329.999255

In [19]:
#top10 = final_df.loc[final_df['profit'] > 300]
#top = final_df.head(10)
top10 = final_df.nlargest(10, 'profit')
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.449459
794,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
17,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.783777
240,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.544677
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.316061

-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [20]:
# Write your code for dropping duplicate values here
final_df.drop_duplicates(inplace=True)

In [21]:
# Write code for repeating subtask 2 here
top10= final_df.nlargest(10, 'profit')
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.449459
794,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.783777
240,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.544677
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.316061
439,Gary Ross,673.0,407.999255,Adventure|Drama|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games,701607,1959.0,English,78.0,2012.0,7.3,140000,329.999255

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

-  ### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [22]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'
final_df = final_df[final_df['num_voted_users']>25000]
IMDb_Top_250 = final_df.nlargest(250,'imdb_score')
IMDb_Top_250

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
1937,Frank Darabont,199.0,28.341469,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,25.00,1994.0,9.3,108000,3.341469
3466,Francis Ford Coppola,208.0,134.821952,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6.00,1972.0,9.2,43000,128.821952
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.00,2008.0,9.0,37000,348.316061
2837,Francis Ford Coppola,149.0,57.300000,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650.0,English,13.00,1974.0,9.0,14000,44.300000
339,Peter Jackson,328.0,377.019252,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189.0,English,94.00,2003.0,8.9,16000,283.019252
3355,Quentin Tarantino,215.0,107.930000,Crime|Drama,Bruce Willis,Pulp Fiction,1324680,2195.0,English,8.00,1994.0,8.9,45000,99.930000
1874,Steven Spielberg,174.0,96.067179,Biography|Drama|History,Liam Neeson,Schindler's List,865020,1273.0,English,22.00,1993.0,8.9,41000,74.067179
4498,Sergio Leone,181.0,6.100000,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.20,1966.0,8.9,20000,4.900000
836,Robert Zemeckis,149.0,329.691196,Comedy|Drama,Tom Hanks,Forrest Gump,1251222,1398.0,English,55.00,1994.0,8.8,59000,274.691196
2051,Irvin Kershner,223.0,290.158751,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode V - The Empire Strikes Back,837759,900.0,English,18.00,1980.0,8.8,17000,272.158751
270,Peter Jackson,297.0,313.837577,Action|Adventure|Drama|Fantasy,Christopher Lee,The Lord of the Rings: The Fellowship of the R...,1238746,5060.0,English,93.00,2001.0,8.8,21000,220.837577
97,Christopher Nolan,642.0,292.568851,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160.00,2010.0,8.8,175000,132.568851
683,David Fincher,315.0,37.023395,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63.00,1999.0,8.8,48000,-25.976605
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.00,1977.0,8.7,33000,449.935665
340,Peter Jackson,294.0,340.478898,Action|Adventure|Drama|Fantasy,Christopher Lee,The Lord of the Rings: The Two Towers,1100446,2417.0,English,94.00,2002.0,8.7,10000,246.478898
654,Lana Wachowski,313.0,171.383253,Action|Sci-Fi,Keanu Reeves,The Matrix,1217752,3646.0,English,63.00,1999.0,8.7,25000,108.383253
3867,Milos Forman,149.0,112.000000,Drama,Scatman Crothers,One Flew Over the Cuckoo's Nest,680041,760.0,English,4.40,1975.0,8.7,32000,107.600000
1903,Martin Scorsese,192.0,46.836394,Biography|Crime|Drama,Robert De Niro,Goodfellas,728685,989.0,English,25.00,1990.0,8.7,25000,21.836394
4029,Fernando Meirelles,214.0,7.563397,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.30,2002.0,8.7,28000,4.263397
4747,Akira Kurosawa,153.0,0.269061,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.00,1954.0,8.7,11000,-1.730939
648,Steven Spielberg,219.0,216.119491,Action|Drama|War,Tom Hanks,Saving Private Ryan,881236,2277.0,English,70.00,1998.0,8.6,22000,146.119491
2158,Jonathan Demme,185.0,130.727000,Crime|Drama|Horror|Thriller,Anthony Hopkins,The Silence of the Lambs,887467,916.0,English,19.00,1991.0,8.6,40000,111.727000
1600,David Fincher,216.0,100.125340,Crime|Drama|Mystery|Thriller,Morgan Freeman,Se7en,1023511,1080.0,English,33.00,1995.0,8.6,39000,67.125340
96,Christopher Nolan,712.0,187.991439,Adventure|Drama|Sci-Fi,Matthew McConaughey,Interstellar,928227,2725.0,English,165.00,2014.0,8.6,349000,22.991439
3592,Bryan Singer,162.0,23.272306,Crime|Drama|Mystery|Thriller,Kevin Spacey,The Usual Suspects,740918,1182.0,English,6.00,1995.0,8.6,28000,17.272306
3175,Tony Kaye,162.0,6.712241,Crime|Drama,Ethan Suplee,American History X,782437,1420.0,English,7.50,1998.0,8.6,35000,-0.787759
4427,Charles Chaplin,120.0,0.163245,Comedy|Drama|Family,Paulette Goddard,Modern Times,143086,211.0,English,1.50,1936.0,8.6,0,-1.336755
2373,Hayao Miyazaki,246.0,10.049886,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,19.00,2001.0,8.6,28000,-8.950114
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.00,1994.0,8.5,17000,377.783777
2152,Steven Spielberg,234.0,242.374454,Action|Adventure,Harrison Ford,Raiders of the Lost Ark,661017,771.0,English,18.00,1981.0,8.5,16000,224.374454
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3361,Jonathan Dayton,270.0,59.889948,Comedy|Drama,Steve Carell,Little Miss Sunshine,355810,889.0,English,8.00,2006.0,7.9,15000,51.889948
1884,Brian De Palma,123.0,76.270454,Crime|Drama|Thriller,Robert De Niro,The Untouchables,219008,418.0,English,25.00,1987.0,7.9,0,51.270454
3452,Paul Haggis,287.0,54.557348,Crime|Drama|Thriller,Don Cheadle,Crash,361169,1624.0,English,6.50,2004.0,7.9,18000,48.057348
4821,John Carpenter,318.0,47.000000,Horror|Thriller,Jamie Lee Curtis,Halloween,157863,1191.0,English,0.30,1978.0,7.9,12000,46.700000
2492,John Carpenter,318.0,47.000000,Horror|Thriller,Jamie Lee Curtis,Halloween,157857,1191.0,English,0.30,1978.0,7.9,12000,46.700000
2177,Tim Burton,111.0,56.362352,Fantasy|Romance,Johnny Depp,Edward Scissorhands,357581,588.0,English,20.00,1990.0,7.9,16000,36.362352
23,Peter Jackson,509.0,258.355354,Adventure|Fantasy,Aidan Turner,The Hobbit: The Desolation of Smaug,483540,951.0,English,225.00,2013.0,7.9,83000,33.355354
162,Dean DeBlois,292.0,176.997107,Action|Adventure|Animation|Comedy|Family|Fantasy,Gerard Butler,How to Train Your Dragon 2,221128,343.0,English,145.00,2014.0,7.9,46000,31.997107
1807,John Landis,125.0,54.200000,Action|Comedy|Crime|Music,John Belushi,The Blues Brothers,142448,319.0,English,27.00,1980.0,7.9,14000,27.200000
3357,Dan Gilroy,534.0,32.279955,Crime|Drama|Thriller,Jake Gyllenhaal,Nightcrawler,293304,552.0,English,8.50,2014.0,7.9,65000,23.779955
3680,Spike Lee,103.0,27.545445,Drama,Ruby Dee,Do the Right Thing,59524,418.0,English,6.50,1989.0,7.9,0,21.045445
3595,Darren Aronofsky,391.0,26.236603,Drama|Sport,Mark Margolis,The Wrestler,251349,547.0,English,6.00,2008.0,7.9,10000,20.236603
2558,Edgar Wright,285.0,23.618786,Action|Comedy|Mystery,Bill Bailey,Hot Fuzz,352695,687.0,English,8.00,2007.0,7.9,17000,15.618786
2666,James Ivory,58.0,22.954968,Drama|Romance,Anthony Hopkins,The Remains of the Day,45703,156.0,English,11.50,1993.0,7.9,0,11.454968
2667,Paul Thomas Anderson,153.0,26.384919,Drama,Don Cheadle,Boogie Nights,189032,560.0,English,15.00,1997.0,7.9,0,11.384919
706,Quentin Tarantino,596.0,54.116191,Crime|Drama|Mystery|Thriller|Western,Craig Stark,The Hateful Eight,272839,1018.0,English,44.00,2015.0,7.9,114000,10.116191
4931,John Carney,232.0,9.437933,Drama|Music|Romance,Glen Hansard,Once,90827,329.0,English,0.18,2007.0,7.9,26000,9.257933
1713,Edward Zwick,60.0,26.830000,Drama|History|War,Denzel Washington,Glory,101888,365.0,English,18.00,1989.0,7.9,0,8.830000
2418,Edward Zwick,60.0,26.830000,Drama|History|War,Denzel Washington,Glory,101889,365.0,English,18.00,1989.0,7.9,0,8.830000
4082,Richard Linklater,405.0,8.114507,Drama|Romance,Seamus Davey-Fitzpatrick,Before Midnight,95362,270.0,English,3.00,2013.0,7.9,62000,5.114507
4640,Cristian Mungiu,233.0,1.185783,Drama,Anamaria Marinca,"4 Months, 3 Weeks and 2 Days",44763,172.0,Romanian,0.59,2007.0,7.9,14000,0.595783
3768,Duncan Jones,415.0,5.009677,Drama|Mystery|Sci-Fi,Kevin Spacey,Moon,260607,485.0,English,5.00,2009.0,7.9,47000,0.009677
4415,FabiÃ¡n Bielinsky,94.0,1.221261,Crime|Drama|Thriller,Ricardo DarÃ­n,Nine Queens,38215,125.0,Spanish,1.50,2000.0,7.9,0,-0.278739
3677,Christophe Barratier,112.0,3.629758,Drama|Music,Jean-Baptiste Maunier,The Chorus,44151,110.0,French,5.50,2004.0,7.9,0,-1.870242
3510,Yash Chopra,29.0,2.921738,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.00,2004.0,7.9,2000,-4.078262
2863,Clint Eastwood,251.0,13.753931,Drama|History|War,Yuki Matsuzaki,Letters from Iwo Jima,132149,316.0,Japanese,19.00,2006.0,7.9,5000,-5.246069
1813,Philip Kaufman,80.0,21.500000,Adventure|Drama|History,Dennis Quaid,The Right Stuff,45271,170.0,English,27.00,1983.0,7.9,0,-5.500000
3264,Michael Haneke,447.0,0.225377,Drama|Romance,Isabelle Huppert,Amour,70382,190.0,French,8.90,2012.0,7.9,33000,-8.674623
2449,Tim Burton,148.0,5.887457,Biography|Comedy|Drama,Johnny Depp,Ed Wood,142416,420.0,English,18.00,1994.0,7.9,0,-12.112543
1993,Roger Donaldson,126.0,5.128124,Biography|Drama|Sport,Anthony Hopkins,The World's Fastest Indian,44198,251.0,English,25.00,2005.0,7.9,11000,-19.871876

In [23]:
IMDb_Top_250['Rank'] = range(1, 1+len(IMDb_Top_250))
IMDb_Top_250

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,Rank
1937,Frank Darabont,199.0,28.341469,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,25.00,1994.0,9.3,108000,3.341469,1
3466,Francis Ford Coppola,208.0,134.821952,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6.00,1972.0,9.2,43000,128.821952,2
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.00,2008.0,9.0,37000,348.316061,3
2837,Francis Ford Coppola,149.0,57.300000,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650.0,English,13.00,1974.0,9.0,14000,44.300000,4
339,Peter Jackson,328.0,377.019252,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189.0,English,94.00,2003.0,8.9,16000,283.019252,5
3355,Quentin Tarantino,215.0,107.930000,Crime|Drama,Bruce Willis,Pulp Fiction,1324680,2195.0,English,8.00,1994.0,8.9,45000,99.930000,6
1874,Steven Spielberg,174.0,96.067179,Biography|Drama|History,Liam Neeson,Schindler's List,865020,1273.0,English,22.00,1993.0,8.9,41000,74.067179,7
4498,Sergio Leone,181.0,6.100000,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.20,1966.0,8.9,20000,4.900000,8
836,Robert Zemeckis,149.0,329.691196,Comedy|Drama,Tom Hanks,Forrest Gump,1251222,1398.0,English,55.00,1994.0,8.8,59000,274.691196,9
2051,Irvin Kershner,223.0,290.158751,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode V - The Empire Strikes Back,837759,900.0,English,18.00,1980.0,8.8,17000,272.158751,10
270,Peter Jackson,297.0,313.837577,Action|Adventure|Drama|Fantasy,Christopher Lee,The Lord of the Rings: The Fellowship of the R...,1238746,5060.0,English,93.00,2001.0,8.8,21000,220.837577,11
97,Christopher Nolan,642.0,292.568851,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160.00,2010.0,8.8,175000,132.568851,12
683,David Fincher,315.0,37.023395,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63.00,1999.0,8.8,48000,-25.976605,13
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.00,1977.0,8.7,33000,449.935665,14
340,Peter Jackson,294.0,340.478898,Action|Adventure|Drama|Fantasy,Christopher Lee,The Lord of the Rings: The Two Towers,1100446,2417.0,English,94.00,2002.0,8.7,10000,246.478898,15
654,Lana Wachowski,313.0,171.383253,Action|Sci-Fi,Keanu Reeves,The Matrix,1217752,3646.0,English,63.00,1999.0,8.7,25000,108.383253,16
3867,Milos Forman,149.0,112.000000,Drama,Scatman Crothers,One Flew Over the Cuckoo's Nest,680041,760.0,English,4.40,1975.0,8.7,32000,107.600000,17
1903,Martin Scorsese,192.0,46.836394,Biography|Crime|Drama,Robert De Niro,Goodfellas,728685,989.0,English,25.00,1990.0,8.7,25000,21.836394,18
4029,Fernando Meirelles,214.0,7.563397,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.30,2002.0,8.7,28000,4.263397,19
4747,Akira Kurosawa,153.0,0.269061,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.00,1954.0,8.7,11000,-1.730939,20
648,Steven Spielberg,219.0,216.119491,Action|Drama|War,Tom Hanks,Saving Private Ryan,881236,2277.0,English,70.00,1998.0,8.6,22000,146.119491,21
2158,Jonathan Demme,185.0,130.727000,Crime|Drama|Horror|Thriller,Anthony Hopkins,The Silence of the Lambs,887467,916.0,English,19.00,1991.0,8.6,40000,111.727000,22
1600,David Fincher,216.0,100.125340,Crime|Drama|Mystery|Thriller,Morgan Freeman,Se7en,1023511,1080.0,English,33.00,1995.0,8.6,39000,67.125340,23
96,Christopher Nolan,712.0,187.991439,Adventure|Drama|Sci-Fi,Matthew McConaughey,Interstellar,928227,2725.0,English,165.00,2014.0,8.6,349000,22.991439,24
3592,Bryan Singer,162.0,23.272306,Crime|Drama|Mystery|Thriller,Kevin Spacey,The Usual Suspects,740918,1182.0,English,6.00,1995.0,8.6,28000,17.272306,25
3175,Tony Kaye,162.0,6.712241,Crime|Drama,Ethan Suplee,American History X,782437,1420.0,English,7.50,1998.0,8.6,35000,-0.787759,26
4427,Charles Chaplin,120.0,0.163245,Comedy|Drama|Family,Paulette Goddard,Modern Times,143086,211.0,English,1.50,1936.0,8.6,0,-1.336755,27
2373,Hayao Miyazaki,246.0,10.049886,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,19.00,2001.0,8.6,28000,-8.950114,28
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.00,1994.0,8.5,17000,377.783777,29
2152,Steven Spielberg,234.0,242.374454,Action|Adventure,Harrison Ford,Raiders of the Lost Ark,661017,771.0,English,18.00,1981.0,8.5,16000,224.374454,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3361,Jonathan Dayton,270.0,59.889948,Comedy|Drama,Steve Carell,Little Miss Sunshine,355810,889.0,English,8.00,2006.0,7.9,15000,51.889948,221
1884,Brian De Palma,123.0,76.270454,Crime|Drama|Thriller,Robert De Niro,The Untouchables,219008,418.0,English,25.00,1987.0,7.9,0,51.270454,222
3452,Paul Haggis,287.0,54.557348,Crime|Drama|Thriller,Don Cheadle,Crash,361169,1624.0,English,6.50,2004.0,7.9,18000,48.057348,223
4821,John Carpenter,318.0,47.000000,Horror|Thriller,Jamie Lee Curtis,Halloween,157863,1191.0,English,0.30,1978.0,7.9,12000,46.700000,224
2492,John Carpenter,318.0,47.000000,Horror|Thriller,Jamie Lee Curtis,Halloween,157857,1191.0,English,0.30,1978.0,7.9,12000,46.700000,225
2177,Tim Burton,111.0,56.362352,Fantasy|Romance,Johnny Depp,Edward Scissorhands,357581,588.0,English,20.00,1990.0,7.9,16000,36.362352,226
23,Peter Jackson,509.0,258.355354,Adventure|Fantasy,Aidan Turner,The Hobbit: The Desolation of Smaug,483540,951.0,English,225.00,2013.0,7.9,83000,33.355354,227
162,Dean DeBlois,292.0,176.997107,Action|Adventure|Animation|Comedy|Family|Fantasy,Gerard Butler,How to Train Your Dragon 2,221128,343.0,English,145.00,2014.0,7.9,46000,31.997107,228
1807,John Landis,125.0,54.200000,Action|Comedy|Crime|Music,John Belushi,The Blues Brothers,142448,319.0,English,27.00,1980.0,7.9,14000,27.200000,229
3357,Dan Gilroy,534.0,32.279955,Crime|Drama|Thriller,Jake Gyllenhaal,Nightcrawler,293304,552.0,English,8.50,2014.0,7.9,65000,23.779955,230
3680,Spike Lee,103.0,27.545445,Drama,Ruby Dee,Do the Right Thing,59524,418.0,English,6.50,1989.0,7.9,0,21.045445,231
3595,Darren Aronofsky,391.0,26.236603,Drama|Sport,Mark Margolis,The Wrestler,251349,547.0,English,6.00,2008.0,7.9,10000,20.236603,232
2558,Edgar Wright,285.0,23.618786,Action|Comedy|Mystery,Bill Bailey,Hot Fuzz,352695,687.0,English,8.00,2007.0,7.9,17000,15.618786,233
2666,James Ivory,58.0,22.954968,Drama|Romance,Anthony Hopkins,The Remains of the Day,45703,156.0,English,11.50,1993.0,7.9,0,11.454968,234
2667,Paul Thomas Anderson,153.0,26.384919,Drama,Don Cheadle,Boogie Nights,189032,560.0,English,15.00,1997.0,7.9,0,11.384919,235
706,Quentin Tarantino,596.0,54.116191,Crime|Drama|Mystery|Thriller|Western,Craig Stark,The Hateful Eight,272839,1018.0,English,44.00,2015.0,7.9,114000,10.116191,236
4931,John Carney,232.0,9.437933,Drama|Music|Romance,Glen Hansard,Once,90827,329.0,English,0.18,2007.0,7.9,26000,9.257933,237
1713,Edward Zwick,60.0,26.830000,Drama|History|War,Denzel Washington,Glory,101888,365.0,English,18.00,1989.0,7.9,0,8.830000,238
2418,Edward Zwick,60.0,26.830000,Drama|History|War,Denzel Washington,Glory,101889,365.0,English,18.00,1989.0,7.9,0,8.830000,239
4082,Richard Linklater,405.0,8.114507,Drama|Romance,Seamus Davey-Fitzpatrick,Before Midnight,95362,270.0,English,3.00,2013.0,7.9,62000,5.114507,240
4640,Cristian Mungiu,233.0,1.185783,Drama,Anamaria Marinca,"4 Months, 3 Weeks and 2 Days",44763,172.0,Romanian,0.59,2007.0,7.9,14000,0.595783,241
3768,Duncan Jones,415.0,5.009677,Drama|Mystery|Sci-Fi,Kevin Spacey,Moon,260607,485.0,English,5.00,2009.0,7.9,47000,0.009677,242
4415,FabiÃ¡n Bielinsky,94.0,1.221261,Crime|Drama|Thriller,Ricardo DarÃ­n,Nine Queens,38215,125.0,Spanish,1.50,2000.0,7.9,0,-0.278739,243
3677,Christophe Barratier,112.0,3.629758,Drama|Music,Jean-Baptiste Maunier,The Chorus,44151,110.0,French,5.50,2004.0,7.9,0,-1.870242,244
3510,Yash Chopra,29.0,2.921738,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.00,2004.0,7.9,2000,-4.078262,245
2863,Clint Eastwood,251.0,13.753931,Drama|History|War,Yuki Matsuzaki,Letters from Iwo Jima,132149,316.0,Japanese,19.00,2006.0,7.9,5000,-5.246069,246
1813,Philip Kaufman,80.0,21.500000,Adventure|Drama|History,Dennis Quaid,The Right Stuff,45271,170.0,English,27.00,1983.0,7.9,0,-5.500000,247
3264,Michael Haneke,447.0,0.225377,Drama|Romance,Isabelle Huppert,Amour,70382,190.0,French,8.90,2012.0,7.9,33000,-8.674623,248
2449,Tim Burton,148.0,5.887457,Biography|Comedy|Drama,Johnny Depp,Ed Wood,142416,420.0,English,18.00,1994.0,7.9,0,-12.112543,249
1993,Roger Donaldson,126.0,5.128124,Biography|Drama|Sport,Anthony Hopkins,The World's Fastest Indian,44198,251.0,English,25.00,2005.0,7.9,11000,-19.871876,250

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [24]:
# Write your code for extracting the top 10 directors here
directors = final_df.groupby('director_name')['imdb_score'].mean()
#directors.loc[directors.index == 'Damien Chazelle']
directors = directors.sort_values(ascending=True)

top10directors = directors.nlargest(10)
#final_df.loc[final_df['director_name'] == 'Damien Chazelle']
top10directors

director_name
Akira Kurosawa       8.700000
Tony Kaye            8.600000
Charles Chaplin      8.600000
Alfred Hitchcock     8.500000
Damien Chazelle      8.500000
Majid Majidi         8.500000
Sergio Leone         8.433333
Christopher Nolan    8.425000
Richard Marquand     8.400000
S.S. Rajamouli       8.400000
Name: imdb_score, dtype: float64

**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [25]:
final_df['genres_1'] = ''
final_df['genres_2'] = ''

final_df['genres_1']= final_df['genres'].apply(lambda x: str(x).split('|',2)[:1])
final_df['genres_2']= final_df['genres'].apply(lambda x: str(x).split('|',2)[1:2])

final_df['genres_1'] = final_df['genres_1'].str.get(0)
final_df['genres_2'] = final_df['genres_2'].str.get(0)

final_df

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genres_1,genres_2
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.000,2009.0,7.9,33000,523.505847,Action,Adventure
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.000,2015.0,7.0,150000,502.177271,Action,Adventure
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.000,1997.0,7.7,26000,458.672302,Drama,Romance
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.000,1977.0,8.7,33000,449.935665,Action,Adventure
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.500,1982.0,7.9,34000,424.449459,Family,Sci-Fi
794,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.000,2012.0,8.1,123000,403.279547,Action,Adventure
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.000,1994.0,8.5,17000,377.783777,Adventure,Animation
240,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.000,1999.0,6.5,13000,359.544677,Action,Adventure
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.000,2008.0,9.0,37000,348.316061,Action,Crime
439,Gary Ross,673.0,407.999255,Adventure|Drama|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games,701607,1959.0,English,78.000,2012.0,7.3,140000,329.999255,Adventure,Drama
812,Tim Miller,579.0,363.024263,Action|Adventure|Comedy|Romance|Sci-Fi,Ryan Reynolds,Deadpool,479047,1058.0,English,58.000,2016.0,8.1,117000,305.024263,Action,Adventure
186,Francis Lawrence,502.0,424.645577,Adventure|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games: Catching Fire,498397,706.0,English,130.000,2013.0,7.6,82000,294.645577,Adventure,Sci-Fi
697,Steven Spielberg,308.0,356.784000,Adventure|Sci-Fi|Thriller,Wayne Knight,Jurassic Park,613473,895.0,English,63.000,1993.0,8.1,19000,293.784000,Adventure,Sci-Fi
521,Pierre Coffin,306.0,368.049635,Animation|Comedy|Family|Sci-Fi,Steve Carell,Despicable Me 2,286877,284.0,English,76.000,2013.0,7.5,56000,292.049635,Animation,Comedy
814,Clint Eastwood,490.0,350.123553,Action|Biography|Drama|History|Thriller|War,Bradley Cooper,American Sniper,325264,916.0,English,58.800,2014.0,7.3,112000,291.323553,Action,Biography
338,Andrew Stanton,301.0,380.838870,Adventure|Animation|Comedy|Family,Alexander Gould,Finding Nemo,692482,866.0,English,94.000,2003.0,8.2,11000,286.838870,Adventure,Animation
582,Andrew Adamson,205.0,436.471036,Adventure|Animation|Comedy|Family|Fantasy|Romance,Rupert Everett,Shrek 2,314630,483.0,English,150.000,2004.0,7.2,0,286.471036,Adventure,Animation
339,Peter Jackson,328.0,377.019252,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189.0,English,94.000,2003.0,8.9,16000,283.019252,Action,Adventure
1536,Richard Marquand,197.0,309.125409,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode VI - Return of the Jedi,681857,647.0,English,32.500,1983.0,8.4,14000,276.625409,Action,Adventure
836,Robert Zemeckis,149.0,329.691196,Comedy|Drama,Tom Hanks,Forrest Gump,1251222,1398.0,English,55.000,1994.0,8.8,59000,274.691196,Comedy,Drama
2051,Irvin Kershner,223.0,290.158751,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode V - The Empire Strikes Back,837759,900.0,English,18.000,1980.0,8.8,17000,272.158751,Action,Adventure
2601,Chris Columbus,102.0,285.761243,Comedy|Family,Macaulay Culkin,Home Alone,311075,305.0,English,18.000,1990.0,7.5,20000,267.761243,Comedy,Family
236,George Lucas,359.0,380.262555,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode III - Revenge of the Sith,520104,3286.0,English,113.000,2005.0,7.6,10000,267.262555,Action,Adventure
161,Sam Raimi,291.0,403.706375,Action|Adventure|Fantasy|Romance,J.K. Simmons,Spider-Man,544665,2012.0,English,139.000,2002.0,7.3,5000,264.706375,Action,Adventure
563,Kyle Balda,308.0,336.029560,Action|Animation|Comedy|Family|Sci-Fi,Steve Carell,Minions,142403,275.0,English,74.000,2015.0,6.4,70000,262.029560,Action,Animation
1181,M. Night Shyamalan,234.0,293.501675,Drama|Mystery|Thriller,Bruce Willis,The Sixth Sense,704766,2073.0,English,40.000,1999.0,8.1,14000,253.501675,Drama,Mystery
2917,Steven Spielberg,385.0,260.000000,Adventure|Drama|Thriller,Roy Scheider,Jaws,412454,962.0,English,8.000,1975.0,8.0,21000,252.000000,Adventure,Drama
125,Chris Buck,406.0,400.736600,Adventure|Animation|Comedy|Family|Fantasy|Musical,Josh Gad,Frozen,421658,904.0,English,150.000,2013.0,7.6,58000,250.736600,Adventure,Animation
926,Chris Weitz,299.0,296.623634,Adventure|Drama|Fantasy|Romance,Robert Pattinson,The Twilight Saga: New Moon,220758,919.0,English,50.000,2009.0,4.6,13000,246.623634,Adventure,Drama
340,Peter Jackson,294.0,340.478898,Action|Adventure|Drama|Fantasy,Christopher Lee,The Lord of the Rings: The Two Towers,1100446,2417.0,English,94.000,2002.0,8.7,10000,246.478898,Action,Adventure
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22,Ridley Scott,343.0,105.219735,Action|Adventure|Drama|History,Mark Addy,Robin Hood,211765,546.0,English,200.000,2010.0,6.7,17000,-94.780265,Action,Adventure
70,Martin Scorsese,682.0,73.820094,Adventure|Drama|Family|Mystery,ChloÃ« Grace Moretz,Hugo,245333,678.0,English,170.000,2011.0,7.5,42000,-96.179906,Adventure,Drama
203,Robert Schwentke,208.0,33.592415,Action|Comedy|Fantasy,Ryan Reynolds,R.I.P.D.,91640,210.0,English,130.000,2013.0,5.6,20000,-96.407585,Action,Comedy
88,Brad Bird,443.0,93.417865,Action|Adventure|Family|Mystery|Sci-Fi,Judy Greer,Tomorrowland,128306,497.0,English,190.000,2015.0,6.5,37000,-96.582135,Action,Adventure
105,Wolfgang Petersen,231.0,60.655503,Action|Adventure|Drama|Thriller,Jimmy Bennett,Poseidon,82380,629.0,English,160.000,2006.0,5.6,0,-99.344497,Action,Adventure
315,Ron Clements,127.0,38.120554,Adventure|Animation|Family|Sci-Fi,Joseph Gordon-Levitt,Treasure Planet,71527,217.0,English,140.000,2002.0,7.1,0,-101.879446,Adventure,Animation
164,Rob Cohen,145.0,31.704416,Action|Adventure|Sci-Fi|Thriller,Sam Shepard,Stealth,45455,388.0,English,135.000,2005.0,5.0,0,-103.295584,Action,Adventure
170,Hironobu Sakaguchi,166.0,32.131830,Action|Adventure|Animation|Fantasy|Romance|Sci-Fi,Steve Buscemi,Final Fantasy: The Spirits Within,72259,788.0,English,137.000,2001.0,6.4,0,-104.868170,Action,Adventure
163,Alex Proyas,184.0,31.141074,Action|Adventure|Fantasy,Gerard Butler,Gods of Egypt,51892,273.0,English,140.000,2016.0,5.5,24000,-108.858926,Action,Adventure
51,Mike Newell,306.0,90.755643,Action|Adventure|Fantasy|Romance,Jake Gyllenhaal,Prince of Persia: The Sands of Time,222403,453.0,English,200.000,2010.0,6.6,23000,-109.244357,Action,Adventure
24,Chris Weitz,251.0,70.083519,Adventure|Family|Fantasy,Christopher Lee,The Golden Compass,149019,666.0,English,180.000,2007.0,6.1,0,-109.916481,Adventure,Family
267,Jan de Bont,79.0,48.068396,Action|Crime|Romance|Thriller,Jason Patric,Speed 2: Cruise Control,60573,248.0,English,160.000,1997.0,3.7,894,-111.931604,Action,Crime
108,Duncan Jones,275.0,46.978995,Action|Adventure|Fantasy,Dominic Cooper,Warcraft,111609,781.0,English,160.000,2016.0,7.3,89000,-113.021005,Action,Adventure
3879,Joe Wright,256.0,34.964818,Adventure|Family|Fantasy,Hugh Jackman,Pan,39975,186.0,English,150.000,2015.0,5.8,24000,-115.035182,Adventure,Family
145,Joe Wright,256.0,34.964818,Adventure|Family|Fantasy,Hugh Jackman,Pan,39956,186.0,English,150.000,2015.0,5.8,24000,-115.035182,Adventure,Family
113,Oliver Stone,248.0,34.293771,Action|Adventure|Biography|Drama|History|Roman...,Anthony Hopkins,Alexander,138863,1390.0,English,155.000,2004.0,5.5,0,-120.706229,Action,Adventure
14,Gore Verbinski,450.0,89.289910,Action|Adventure|Western,Johnny Depp,The Lone Ranger,181792,711.0,English,215.000,2013.0,6.5,48000,-125.710090,Action,Adventure
62,Lana Wachowski,384.0,47.375327,Action|Adventure|Sci-Fi,Channing Tatum,Jupiter Ascending,139593,720.0,English,176.000,2015.0,5.4,44000,-128.624673,Action,Adventure
49,Bryan Singer,338.0,65.171860,Adventure|Fantasy,Eddie Marsan,Jack the Giant Slayer,106416,205.0,English,195.000,2013.0,6.3,22000,-129.828140,Adventure,Fantasy
85,Carl Rinsch,218.0,38.297305,Action|Adventure|Drama|Fantasy,Keanu Reeves,47 Ronin,116994,324.0,English,175.000,2013.0,6.3,35000,-136.702695,Action,Adventure
28,Peter Berg,377.0,65.173160,Action|Adventure|Sci-Fi|Thriller,Liam Neeson,Battleship,202382,751.0,English,209.000,2012.0,5.9,44000,-143.826840,Action,Adventure
91,Robert Zemeckis,188.0,0.665426,Adventure|Animation|Family|Fantasy,Tom Hanks,The Polar Express,120798,444.0,English,165.000,2004.0,6.6,10000,-164.334574,Adventure,Animation
3659,Prachya Pinkaew,112.0,11.905519,Action|Crime|Drama|Thriller,Jon Foo,The Protector,30210,214.0,Thai,200.000,2005.0,7.1,0,-188.094481,Action,Crime
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.700,2012.0,6.6,24000,-190.641321,Action,Adventure
1016,Luc Besson,111.0,14.131298,Adventure|Biography|Drama|History|War,Paul Brooke,The Messenger: The Story of Joan of Arc,55889,390.0,English,390.000,1999.0,6.4,0,-375.868702,Adventure,Biography
1338,John Woo,160.0,0.626809,Action|Adventure|Drama|History|War,Takeshi Kaneshiro,Red Cliff,36894,105.0,Mandarin,553.632,2008.0,7.4,0,-553.005191,Action,Adventure
3423,Katsuhiro Ã”tomo,150.0,0.439162,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430.0,Japanese,1100.000,1988.0,8.1,0,-1099.560838,Action,Animation
2323,Hayao Miyazaki,174.0,2.298191,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2400.000,1997.0,8.4,11000,-2397.701809,Adventure,Animation
3859,Chan-wook Park,202.0,0.211667,Crime|Drama,Min-sik Choi,Lady Vengeance,53508,131.0,Korean,4200.000,2005.0,7.7,4000,-4199.788333,Crime,Drama
2988,Joon-ho Bong,363.0,2.201412,Comedy|Drama|Horror|Sci-Fi,Doona Bae,The Host,68883,279.0,Korean,12215.500,2006.0,7.0,7000,-12213.298588,Comedy,Drama

In [26]:
pop = final_df.groupby(['genres_1','genres_2'])['gross'].mean()  
pop = pop.sort_values(ascending=True)
PopGenre = pop.nlargest(6)

In [27]:
PopGenre

genres_1   genres_2
Family     Sci-Fi       434.949459
Adventure  Sci-Fi       228.627758
Musical    Romance      181.360000
Adventure  Family       162.267439
           Animation    143.978551
Drama      Western      131.981047
Name: gross, dtype: float64

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [30]:
# Write your code for creating three new dataframes here
Leo_Caprio = final_df.loc[final_df['actor_1_name'] == 'Leonardo DiCaprio']
Meryl_Streep = final_df.loc[final_df['actor_1_name'] == 'Meryl Streep']
Brad_Pit = final_df.loc[final_df['actor_1_name'] == 'Brad Pitt']

In [33]:
# Write your code for combining the three dataframes here
result_1 = pd.concat([Leo_Caprio,Meryl_Streep], ignore_index=True)
result = pd.concat([result_1,Brad_Pit],ignore_index=True)

In [40]:
# Write your code for grouping the combined dataframe here
best = result.groupby(['actor_1_name'])['num_critic_for_reviews'].mean()
best_u = result.groupby(['actor_1_name'])['num_user_for_reviews'].mean()
best = best.sort_values(ascending=False)
best_u = best_u.sort_values(ascending=False)
print(best)
print("-----------")
print(best_u)
#best[best.index == 'Leonardo DiCaprio']
#best.nlargest(5,'num_user_for_reviews')

actor_1_name
Leonardo DiCaprio    344.450000
Brad Pitt            252.125000
Meryl Streep         191.222222
Name: num_critic_for_reviews, dtype: float64
-----------
actor_1_name
Leonardo DiCaprio    956.650000
Brad Pitt            784.937500
Meryl Streep         319.666667
Name: num_user_for_reviews, dtype: float64

In [41]:
# Write the code for finding the mean of critic reviews and audience reviews here
#best[best.index == 'Leonardo DiCaprio']
best_u= best_u.sort_values(ascending=False)
best_u.head()

actor_1_name
Leonardo DiCaprio    956.650000
Brad Pitt            784.937500
Meryl Streep         319.666667
Name: num_user_for_reviews, dtype: float64


**Checkpoint 6:** `Leonardo` has aced both the lists!